# FROM ghcr.io/codbex/codbex-gaia:2.46.0
FROM ghcr.io/codbex/codbex-atlas:2.71.0

COPY node_modules/@codbex target/dirigible/repository/root/registry/public/

ENV DIRIGIBLE_HOME_URL=/services/web/dashboard/
